### ISSUE TITLE
Exception while exporting the Architect Call flow using CX as Code

### ISSUE THREAD

**Issue by Vigneshkumar77** [MyPureCloud/terraform-provider-genesyscloud#278]
Hello,
I am using the Genesys Cloud provider version 1.3.0. I am trying to export Genesys cloud Call flow using CX as code. But while doing that I am getting below exception. Kindly help on this.

Error: Failed to get page of IVR configs: API Error: 403 - Unable to perform the requested action. You are missing the following permission(s): com.inin.pubapi.iam.util.ResourcePermission

Regards,
Vignesh Kumar A

**Comment by ronanwatkins** [comment]
Hi,

You need to apply the correct permissions to your OAuth client for CX as Code to make public API calls.
I'm not sure which exact permissions are required to read IVRs but applying all architect view permissions should solve the problem.

**Comment by Vigneshkumar77** [comment]
Hi,
I have applied all the architect related permission to the OAuth Client credential that I am using in Cx as code. But still the issue persist.

**Comment by Vigneshkumar77** [comment]
Hi,
There was a routing permission that needs to be granted. After applying that there is no more error. but the file that gets exported just has Genesys cloud provider details. Nothing related to the call flow. Kindly help me on this.

**Comment by dmizin** [comment]
Same here as OP. No files containing config are being exported. Using v 1.4.0 plugin. Using this:
`resource "genesyscloud_tf_export" "export" {
  directory          = "./genesyscloud"
  resource_types     = ["genesyscloud_flow"]
  #include_state_file = true
  export_as_hcl = true`

Produces this:
`terraform {
  required_providers {
    genesyscloud = {
      source  = "registry.terraform.io/mypurecloud/genesyscloud"
      version = "1.4.0"
    }
  }
}

resource "genesyscloud_flow" "[edited]" {
  filepath = "${var.[edited]_filepath}"
}`

And .tfvars file contains this:
`// This file has been autogenerated. The following properties could not be retrieved from the API or would not make sense in a different org e.g. Edge IDs
// The variables contained in this file have been given default values and should be edited as necessary

genesyscloud_flow_[edited]_filepath = ""`

Does the export for Architect Flows actually supposed to work? Permissions are checked and role used has all Architect permissions.

**Comment by ronanwatkins** [comment]
At the moment, there is no way to download the file used to generate a flow.
So if you want to export the flow configuration to a new org you will need to source the file by other means and provide the filepath in the `.tfvars` file

**Comment by carnellj** [comment]
Hi Dmzin,

We currently do no support the exporting of Architect flows in the CX as Code resource.  It is on our roadmap, but there is no timeline yet for when we start this work.  You can export the flows using the Archy CLI tool.  The Archy CLI tool has an export feature in it.  I wrote a blog post several months ago that demonstrates how to use the CLI to export flows:  https://developer.genesys.cloud/blog/2021-11-06-exporting-archy-flows-in-bulk/.  Hope that helps.

Thanks,
     John Carnell
