### ISSUE TITLE
1.4.0 version -  errors with members_id fields

### ISSUE THREAD

**Issue by motomeru** [MyPureCloud/terraform-provider-genesyscloud#295]
Hey, 

in my scenario, I create objects (groups, queues - without members) with terraform, but assigment to that objects is done by supervisor (manual process).

example group tf configuration:

```
resource "genesyscloud_group" "supervisorGroup" {
  name          = "Supervisor Group"
  description   = "Group for Supervisors"
  type          = "official"
  visibility    = "members"
  rules_visible = true
  owner_ids = [
    data.genesyscloud_user.motomeru.id,

  ]
  # member_ids    = []
  addresses {
    number = "111111111"
    type   = "GROUPRING"
  }
}
```

to version 1.3.0 its worked perfect, like you see on my code i commented member_ids field, yesterday when I updated version to 1.4.0 I see on each apply:

Error: mismatch on attribute member_ids.1311397769: expected value: <nil> actual value:
with genesyscloud_group.supervisorGroup
on genesyscloud_group.tf line 17, in resource "genesyscloud_group" "supervisorGroup":
resource "genesyscloud_group" "supervisorGroup" {

scenario to reproduce on 1.4.0:

1. create terraform group without member_ids 
2. add manually agent as an indyvidual member
3. run terraform apply 
4. received an error about mismatch

that work ok on version 1.3.0 and 0.14.1, ( I have two diffrent  customers using terraform with that assigment process )

BR,
David

**Comment by ronanwatkins** [comment]
Hi David,

I'll look into this issue to see what fix I can apply to it.
The function returning the error here is a solution I added to solve eventual consistency problems and it seems to be tripping up with this scenario.

**Comment by ronanwatkins** [comment]
Hi,

I've merged in a fix for this bug. I'll include it in the next release.

**Comment by motomeru** [comment]
Hi @carnellj I see that you closed that ticket, I checked configuration on 1.4.0 still have the same issue.

`Error: mismatch on attribute member_ids.1827314773: expected value: <nil> actual value:
with genesyscloud_group.plannerAdminGroup
on genesyscloud_group.tf line 84, in resource "genesyscloud_group" "plannerAdminGroup":
resource "genesyscloud_group" "plannerAdminGroup" {`
